name: home
timestamp: 1527866758
version: 7
preset:
  name: new
  image: 'gantry-admin://images/layouts/default.png'
  timestamp: 1526047700
positions: {  }
sections:
  top: Top
  navigation: Navigation
  showcase: Showcase
  utility: Utility
  features: Features
  subfeatures: Subfeatures
  modules: Modules
  above: Above
  system: System
  mainbar: Mainbar
  sidebar: Sidebar
  below: Below
  addons: Addons
  extended: Extended
  expanded: Expanded
  bottom: Bottom
  copyright: Copyright
  header: Header
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-6223: 'System Messages'
  content:
    system-content-9877: 'Page Content'
  social:
    social-1333: Social
    social-2110: Social
  wpfc-image:
    wpfc-image-3641: Image
  menu:
    menu-6974: Menu
  wpfc-content-grid:
    wpfc-content-grid-6479: 'Content Grid'
  wpfc-list:
    wpfc-list-2512: List
  wpfc-contact-info:
    wpfc-contact-info-1240: 'Contact Info'
  copyright:
    copyright-9002: Copyright
  logo:
    logo-6114: 'Logo / Image'
  mobile-menu:
    mobile-menu-9728: 'Mobile Menu'
inherit:
  default:
    top: top
    navigation: navigation
    footer: footer
    copyright: copyright
    offcanvas: offcanvas
    social-1333: social-9544
    social-2110: social-2101
    wpfc-image-3641: wpfc-image-3703
    menu-6974: menu-5372
    wpfc-content-grid-6479: wpfc-content-grid-2457
    wpfc-list-2512: wpfc-list-8215
    wpfc-contact-info-1240: wpfc-contact-info-4790
    copyright-9002: copyright-9638
    logo-6114: logo-4087
    mobile-menu-9728: mobile-menu-3499
