version: 2
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1525891392
layout:
  /mainbar/:
    -
      - system-messages-7750
    -
      - system-content-3835
structure:
  mainbar:
    type: section
    attributes:
      boxed: ''
