name: _body_only
timestamp: 1527901639
version: 7
preset:
  name: default
  image: 'gantry-admin://images/layouts/default.png'
  timestamp: 1527866652
positions:
  base-sidebar: 'Base Sidebar'
sections:
  top: Top
  navigation: Navigation
  showcase: Showcase
  utility: Utility
  features: Features
  subfeatures: Subfeatures
  modules: Modules
  above: Above
  system: System
  mainbar: Mainbar
  sidebar: Sidebar
  below: Below
  addons: Addons
  extended: Extended
  expanded: Expanded
  bottom: Bottom
  copyright: Copyright
  header: Header
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles:
  social:
    social-9544: Social
    social-2101: Social
  wpfc-image:
    wpfc-image-3703: Image
  menu:
    menu-5372: Menu
  wpfc-hero:
    wpfc-hero-6626: Hero
  widget:
    position-widget-5481: Breadcrumbs
    position-widget-7342: Widget
  messages:
    system-messages-3486: 'System Messages'
  content:
    system-content-7751: 'Page Content'
  position:
    position-position-9989: 'Base Sidebar'
  wpfc-content-grid:
    wpfc-content-grid-2457: 'Content Grid'
  wpfc-list:
    wpfc-list-8215: List
  wpfc-contact-info:
    wpfc-contact-info-4790: 'Contact Info'
  copyright:
    copyright-9638: Copyright
  logo:
    logo-4087: 'Logo / Image'
  mobile-menu:
    mobile-menu-3499: 'Mobile Menu'
inherit: {  }
