version: 2
preset:
  name: _offline
  image: 'gantry-admin://images/layouts/default.png'
  timestamp: 1526458237
layout:
  top: {  }
  /header/: {  }
  /wrapper-navigation/:
    navigation: {  }
  /showcase/: {  }
  /utility/: {  }
  /features/: {  }
  /subfeatures/: {  }
  /modules/: {  }
  /above/: {  }
  /system/:
    -
      - system-messages-6223
  /container-main/:
    -
      -
        '/aside/ 25': {  }
      -
        '/mainbar/ 50':
          -
            - system-content-9877
      -
        '/sidebar/ 25': {  }
  /below/: {  }
  /addons/: {  }
  /extended/: {  }
  /expanded/: {  }
  /bottom/: {  }
  footer: {  }
  copyright: {  }
  offcanvas: {  }
structure:
  top:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  wrapper-navigation:
    attributes:
      name: Wrapper
      boxed: ''
  showcase:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  subfeatures:
    type: section
    attributes:
      boxed: ''
  modules:
    type: section
    attributes:
      boxed: ''
  above:
    type: section
    attributes:
      boxed: ''
  system:
    type: section
    attributes:
      boxed: ''
  aside:
    attributes:
      boxed: '1'
  mainbar:
    type: section
    attributes:
      boxed: '1'
  sidebar:
    type: section
    attributes:
      boxed: '1'
  container-main:
    attributes:
      boxed: ''
      class: 'padding-top-5 padding-bottom-5'
      extra: {  }
  below:
    type: section
    attributes:
      boxed: ''
  addons:
    type: section
    attributes:
      boxed: ''
  extended:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  bottom:
    type: section
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  copyright:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
